# Generated by Django 4.2 on 2025-12-16 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClothesColor",
            fields=[
                (
                    "color",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("rgb_tuple", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "clothes_color",
            },
        ),
        migrations.CreateModel(
            name="Dress",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("style", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_style", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dress_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_sleeve_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_sub_color",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_material",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_print",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_neckline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "dress_collar",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("dress_fit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "dress_detail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "dress_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dress_set",
                        to="ui.clothescolor",
                    ),
                ),
            ],
            options={
                "db_table": "dress",
            },
        ),
        migrations.CreateModel(
            name="Perfume",
            fields=[
                ("perfume_id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("perfume_name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=50)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "rating_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("top", models.TextField(blank=True, null=True)),
                ("middle", models.TextField(blank=True, null=True)),
                ("base", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "perfume",
            },
        ),
        migrations.CreateModel(
            name="PerfumeColor",
            fields=[
                (
                    "mainaccord",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "perfume_color",
            },
        ),
        migrations.CreateModel(
            name="TopBottom",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("style", models.CharField(blank=True, max_length=100, null=True)),
                ("sub_style", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "top_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "top_sleeve_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "top_material",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("top_print", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "top_neckline",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("top_fit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bottom_length",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bottom_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "bottom_material",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("bottom_fit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "color_combo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fit_combo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bottom_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bottom_set",
                        to="ui.clothescolor",
                    ),
                ),
                (
                    "top_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="top_set",
                        to="ui.clothescolor",
                    ),
                ),
            ],
            options={
                "db_table": "top_bottom",
            },
        ),
        migrations.CreateModel(
            name="PerfumeClassification",
            fields=[
                (
                    "perfume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="classification",
                        serialize=False,
                        to="ui.perfume",
                    ),
                ),
                ("fragrance", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "perfume_classification",
            },
        ),
        migrations.CreateModel(
            name="PerfumeSeason",
            fields=[
                (
                    "perfume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="season",
                        serialize=False,
                        to="ui.perfume",
                    ),
                ),
                ("spring", models.FloatField(default=0.0)),
                ("summer", models.FloatField(default=0.0)),
                ("fall", models.FloatField(default=0.0)),
                ("winter", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "perfume_season",
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "perfume",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="score",
                        serialize=False,
                        to="ui.perfume",
                    ),
                ),
                ("season_score", models.FloatField(default=0.0)),
                ("color_score", models.FloatField(default=0.0)),
                ("style_score", models.FloatField(default=0.0)),
                ("myscore", models.FloatField(default=0.0)),
            ],
            options={
                "db_table": "score",
            },
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("season", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "disliked_accord",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bottom_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_bottoms",
                        to="ui.topbottom",
                    ),
                ),
                (
                    "dress_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_dresses",
                        to="ui.dress",
                    ),
                ),
                (
                    "top_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_tops",
                        to="ui.topbottom",
                    ),
                ),
            ],
            options={
                "db_table": "user_info",
            },
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord1",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord1",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord2",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord2",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord3",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord4",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AddField(
            model_name="perfume",
            name="mainaccord5",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord5",
                to="ui.perfumecolor",
            ),
        ),
    ]
