# Generated by Django 4.2 on 2025-12-16 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clothescolor",
            name="color",
            field=models.CharField(
                db_column="color", max_length=100, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="clothescolor",
            name="rgb_tuple",
            field=models.CharField(
                blank=True, db_column="rgb_tuple", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_category",
            field=models.CharField(
                blank=True, db_column="원피스_카테고리", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_collar",
            field=models.CharField(
                blank=True, db_column="원피스_옷깃", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_color",
            field=models.ForeignKey(
                blank=True,
                db_column="원피스_색상",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dress_set",
                to="ui.clothescolor",
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_detail",
            field=models.CharField(
                blank=True, db_column="원피스_디테일", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_fit",
            field=models.CharField(
                blank=True, db_column="원피스_핏", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_length",
            field=models.CharField(
                blank=True, db_column="원피스_기장", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_material",
            field=models.CharField(
                blank=True, db_column="원피스_소재", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_neckline",
            field=models.CharField(
                blank=True, db_column="원피스_넥라인", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_print",
            field=models.CharField(
                blank=True, db_column="원피스_프린트", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_sleeve_length",
            field=models.CharField(
                blank=True, db_column="원피스_소매기장", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="dress_sub_color",
            field=models.CharField(
                blank=True, db_column="원피스_서브색상", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="id",
            field=models.AutoField(
                db_column="식별자", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="style",
            field=models.CharField(
                blank=True, db_column="스타일", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="dress",
            name="sub_style",
            field=models.CharField(
                blank=True, db_column="서브스타일", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="base",
            field=models.TextField(blank=True, db_column="Base", null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="brand",
            field=models.CharField(db_column="Brand", max_length=50),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="country",
            field=models.CharField(
                blank=True, db_column="Country", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="gender",
            field=models.CharField(
                blank=True, db_column="Gender", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="mainaccord1",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord1",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord1",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="mainaccord2",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord2",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord2",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="mainaccord3",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord3",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord3",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="mainaccord4",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord4",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord4",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="mainaccord5",
            field=models.ForeignKey(
                blank=True,
                db_column="mainaccord5",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="p_accord5",
                to="ui.perfumecolor",
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="middle",
            field=models.TextField(blank=True, db_column="Middle", null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="perfume_id",
            field=models.IntegerField(
                db_column="perfume_id", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="perfume_name",
            field=models.CharField(db_column="Perfume", max_length=100),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="rating_count",
            field=models.IntegerField(db_column="RatingCount", default=0),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="rating_value",
            field=models.FloatField(db_column="RatingValue", default=0.0),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="top",
            field=models.TextField(blank=True, db_column="Top", null=True),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="url",
            field=models.CharField(
                blank=True, db_column="url", max_length=500, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="year",
            field=models.IntegerField(blank=True, db_column="Year", null=True),
        ),
        migrations.AlterField(
            model_name="perfumeclassification",
            name="fragrance",
            field=models.CharField(
                blank=True, db_column="fragrance", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfumeclassification",
            name="perfume",
            field=models.OneToOneField(
                db_column="perfume_id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="classification",
                serialize=False,
                to="ui.perfume",
            ),
        ),
        migrations.AlterField(
            model_name="perfumecolor",
            name="color",
            field=models.CharField(
                blank=True, db_column="color", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfumecolor",
            name="mainaccord",
            field=models.CharField(
                db_column="mainaccord",
                max_length=255,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="perfumeseason",
            name="fall",
            field=models.FloatField(db_column="fall", default=0.0),
        ),
        migrations.AlterField(
            model_name="perfumeseason",
            name="perfume",
            field=models.OneToOneField(
                db_column="perfume_id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="season",
                serialize=False,
                to="ui.perfume",
            ),
        ),
        migrations.AlterField(
            model_name="perfumeseason",
            name="spring",
            field=models.FloatField(db_column="spring", default=0.0),
        ),
        migrations.AlterField(
            model_name="perfumeseason",
            name="summer",
            field=models.FloatField(db_column="summer", default=0.0),
        ),
        migrations.AlterField(
            model_name="perfumeseason",
            name="winter",
            field=models.FloatField(db_column="winter", default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="color_score",
            field=models.FloatField(db_column="color_score", default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="myscore",
            field=models.FloatField(db_column="myscore", default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="perfume",
            field=models.OneToOneField(
                db_column="perfume_id",
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="score",
                serialize=False,
                to="ui.perfume",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="season_score",
            field=models.FloatField(db_column="season_score", default=0.0),
        ),
        migrations.AlterField(
            model_name="score",
            name="style_score",
            field=models.FloatField(db_column="style_score", default=0.0),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="bottom_category",
            field=models.CharField(
                blank=True, db_column="하의_카테고리", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="bottom_color",
            field=models.ForeignKey(
                blank=True,
                db_column="하의_색상",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bottom_set",
                to="ui.clothescolor",
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="bottom_fit",
            field=models.CharField(
                blank=True, db_column="하의_핏", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="bottom_length",
            field=models.CharField(
                blank=True, db_column="하의_기장", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="bottom_material",
            field=models.CharField(
                blank=True, db_column="하의_소재", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="color_combo",
            field=models.CharField(
                blank=True, db_column="색상_조합", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="fit_combo",
            field=models.CharField(
                blank=True, db_column="핏_조합", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="id",
            field=models.AutoField(
                db_column="식별자", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="style",
            field=models.CharField(
                blank=True, db_column="스타일", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="sub_style",
            field=models.CharField(
                blank=True, db_column="서브스타일", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_category",
            field=models.CharField(
                blank=True, db_column="상의_카테고리", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_color",
            field=models.ForeignKey(
                blank=True,
                db_column="상의_색상",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="top_set",
                to="ui.clothescolor",
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_fit",
            field=models.CharField(
                blank=True, db_column="상의_핏", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_material",
            field=models.CharField(
                blank=True, db_column="상의_소재", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_neckline",
            field=models.CharField(
                blank=True, db_column="상의_넥라인", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_print",
            field=models.CharField(
                blank=True, db_column="상의_프린트", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="topbottom",
            name="top_sleeve_length",
            field=models.CharField(
                blank=True, db_column="상의_소매기장", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="bottom_id",
            field=models.ForeignKey(
                blank=True,
                db_column="하의_식별자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_bottoms",
                to="ui.topbottom",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="disliked_accord",
            field=models.CharField(
                blank=True, db_column="비선호_향조", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="dress_id",
            field=models.ForeignKey(
                blank=True,
                db_column="원피스_식별자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_dresses",
                to="ui.dress",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="season",
            field=models.CharField(
                blank=True, db_column="계절", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="top_id",
            field=models.ForeignKey(
                blank=True,
                db_column="상의_식별자",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_tops",
                to="ui.topbottom",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="user_id",
            field=models.AutoField(
                db_column="사용자_식별자", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterModelTable(
            name="dress",
            table="원피스",
        ),
        migrations.AlterModelTable(
            name="topbottom",
            table="상의_하의",
        ),
    ]
