# Generated by Django 4.2 on 2025-12-17 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0002_alter_clothescolor_color_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dress",
            name="dress_category",
        ),
        migrations.RemoveField(
            model_name="dress",
            name="dress_sub_color",
        ),
        migrations.RemoveField(
            model_name="topbottom",
            name="color_combo",
        ),
        migrations.RemoveField(
            model_name="topbottom",
            name="fit_combo",
        ),
    ]
