# Generated by Django 4.2 on 2025-12-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0003_remove_dress_dress_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dress",
            name="dress_collar",
        ),
    ]
