# Generated by Django 4.2 on 2025-12-17 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0004_remove_dress_dress_collar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dress",
            name="dress_neckline",
        ),
    ]
