# Generated by Django 4.2 on 2025-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ui", "0005_remove_dress_dress_neckline"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="bottom_category",
            field=models.CharField(
                blank=True, db_column="하의_카테고리", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="bottom_color",
            field=models.CharField(
                blank=True, db_column="하의_색상", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="dress_color",
            field=models.CharField(
                blank=True, db_column="원피스_색상", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="top_category",
            field=models.CharField(
                blank=True, db_column="상의_카테고리", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="top_color",
            field=models.CharField(
                blank=True, db_column="상의_색상", max_length=100, null=True
            ),
        ),
    ]
